apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tool
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Always
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.jbzm:3306"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: "123456"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "1"
              memory: 1000Mi
      imagePullSecrets:
        - name: godhand-regcred
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 10.25.132.10
          - 10.25.63.200
        searches:
          - tool.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: tool
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: wordpress

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size:  "20m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "20m"
spec:
  rules:
    - host: blogjbzm.zhengyiwoaini.top
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /

