apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tool
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "1"
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: tool
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: tool
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size:  "20m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "20m"
spec:
  rules:
    - host: nginx-test.jbzm.top
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /

